"""empty message

Revision ID: 4d22cd97e11a
Revises: 4b239be7667e
Create Date: 2019-02-08 11:24:50.342655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d22cd97e11a'
down_revision = '4b239be7667e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagmap_id'), 'tagmap', ['id'], unique=False)
    op.drop_index('ix_tag_posts_post_id', table_name='tag_posts')
    op.drop_index('ix_tag_posts_tag_id', table_name='tag_posts')
    op.drop_index('uix_1', table_name='tag_posts')
    op.drop_table('tag_posts')
    op.drop_table('post')
    op.drop_index('ix_user_posts_post_id', table_name='user_posts')
    op.drop_index('ix_user_posts_user_id', table_name='user_posts')
    op.drop_index('uix_2', table_name='user_posts')
    op.drop_table('user_posts')
    op.drop_index('ix_tag_text', table_name='tag')
    op.drop_table('tag')
    op.create_index(op.f('ix_papers_citation'), 'papers', ['citation'], unique=True)
    op.create_index(op.f('ix_papers_code'), 'papers', ['code'], unique=True)
    op.create_index(op.f('ix_papers_data'), 'papers', ['data'], unique=True)
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_index(op.f('ix_papers_link'), 'papers', ['link'], unique=True)
    op.create_index(op.f('ix_papers_nickname'), 'papers', ['nickname'], unique=True)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_papers_nickname'), table_name='papers')
    op.drop_index(op.f('ix_papers_link'), table_name='papers')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_data'), table_name='papers')
    op.drop_index(op.f('ix_papers_code'), table_name='papers')
    op.drop_index(op.f('ix_papers_citation'), table_name='papers')
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('text', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tag_text', 'tag', ['text'], unique=True)
    op.create_table('user_posts',
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='user_posts_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('uix_2', 'user_posts', ['user_id', 'post_id'], unique=True)
    op.create_index('ix_user_posts_user_id', 'user_posts', ['user_id'], unique=False)
    op.create_index('ix_user_posts_post_id', 'user_posts', ['post_id'], unique=False)
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('post_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_date', mysql.DATETIME(), nullable=True),
    sa.Column('draft', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tag_posts',
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='tag_posts_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='tag_posts_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('uix_1', 'tag_posts', ['tag_id', 'post_id'], unique=True)
    op.create_index('ix_tag_posts_tag_id', 'tag_posts', ['tag_id'], unique=False)
    op.create_index('ix_tag_posts_post_id', 'tag_posts', ['post_id'], unique=False)
    op.drop_index(op.f('ix_tagmap_id'), table_name='tagmap')
    op.drop_table('tagmap')
    # ### end Alembic commands ###
