"""empty message

Revision ID: 2ceb18543d78
Revises: 72319e9e34c4
Create Date: 2019-02-09 17:02:44.450731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ceb18543d78'
down_revision = '72319e9e34c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'tagmap', 'papers', ['paper_id'], ['id'])
    # op.alter_column('users', 'email',
    #            existing_type=mysql.VARCHAR(length=120),
    #            nullable=False)
    op.alter_column('resources', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint(None, 'tagmap', type_='foreignkey')
    # ### end Alembic commands ###
