"""empty message

Revision ID: 7b250ac636e2
Revises: 2ceb18543d78
Create Date: 2019-02-09 18:25:05.298843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b250ac636e2'
down_revision = '2ceb18543d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('teaching',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('type', sa.String(length=300), nullable=True),
    # sa.Column('name', sa.String(length=300), nullable=True),
    # sa.Column('description', sa.String(length=1500), nullable=True),
    # sa.Column('syllabus', sa.String(length=300), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.alter_column('resources', 'description',
               existing_type=mysql.VARCHAR(length=1500),
               nullable=True)
    # op.create_foreign_key(None, 'tagmap', 'papers', ['paper_id'], ['id'])
    # op.alter_column('users', 'email',
    #            existing_type=mysql.VARCHAR(length=120),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint(None, 'tagmap', type_='foreignkey')
    op.alter_column('resources', 'description',
               existing_type=mysql.VARCHAR(length=1500),
               nullable=False)
    op.drop_table('teaching')
    # ### end Alembic commands ###
