"""empty message

Revision ID: 94b1d3b647ac
Revises: 4b239be7667e
Create Date: 2019-02-08 13:09:17.048391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94b1d3b647ac'
down_revision = '4b239be7667e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'tagmap', 'papers', ['paper_id'], ['id'])
    op.alter_column('users', 'cv',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # op.alter_column('users', 'email',
    #            existing_type=mysql.VARCHAR(length=120),
    #            nullable=False)
    op.alter_column('users', 'website',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'website',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'cv',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint(None, 'tagmap', type_='foreignkey')
    # ### end Alembic commands ###
