"""empty message

Revision ID: a40b54f8328a
Revises: 7a4526a1eb30
Create Date: 2019-02-10 18:52:43.873555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a40b54f8328a'
down_revision = '7a4526a1eb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_foreign_key(None, 'tagmap', 'papers', ['paper_id'], ['id'])
    # op.alter_column('users', 'email',
    #            existing_type=mysql.VARCHAR(length=120),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint(None, 'tagmap', type_='foreignkey')
    op.drop_table('research')
    # ### end Alembic commands ###
